### PR TITLE
fix: Use correct IG embed url

### LINKED ISSUE #399: Fix instagram videos
Instagram videos currently don't work

### PR DESCRIPTION
**Pull request by bastislack**
closes #399

### CODE REVIEW

File: src/components/video/platforms/InstagramPlayer.vue [hunk 1]
```diff
@@ -16,17 +27,11 @@ defineProps<{
...
         scrolling="no"
         title="video"
       ></iframe>
     </div>
-    <Duration
-      v-if="startTime || endTime"
-      :start="startTime"
-      :end="endTime"
-      class="mx-auto mt-2 text-muted-foreground"
-    />
```
Comment (JulianDietzel) [inline src/components/video/platforms/InstagramPlayer.vue:30]: I think that it is nice to keep the duration component. Without it the user does not know when the tricks in the video starts and ends. Instagram videos are usually shorter so this isn't necessary often but there are videos with muliple tricks in it and then it could come in handy (if no start or end time is specified the duration isn't shown anyways).

With YouTube videos the argument could be made that we can simply only show the duration specified but we don't seem to be able to do this with instagram, so no way around showing the duration in numbers to the user, I think.

**Review by JulianDietzel — CHANGES_REQUESTED** [review]
A little sad that we (or at least I) can't display the videos directly in the app anymore but I'm glad you got the previews to to render again. This is a lot nicer and it works on my machine too. To see the videos it redirects me to another tab though  but I guess this is intended.

Apart from my comment on the `Duration` I am happy with this :)

File: src/components/video/platforms/InstagramPlayer.vue (hunk 1 above)
Comment (bastislack) [reply src/components/video/platforms/InstagramPlayer.vue:30]: I removed it under the IG videos because I only added Start + End time to YT videos, so it will never be shown here. Since IG doesn't support the looping for a certain timeframe (and it is actually not easy to see the timestamps that are interesting in the video), I never bothered to try to even track these infos.

Comment (bastislack) [reply src/components/video/platforms/InstagramPlayer.vue:30]: Let me know if this is ok for you!

**Comment by bastislack** [comment]
> A little sad that we (or at least I) can't display the videos directly in the app anymore 

Yes this is really annoying about IG... I hope we can find a better solution for this at some point, but for now I think it's good enough that users can watch the videos somehow.
