### PR TITLE
Fixed validations for number input

### LINKED ISSUE #362: Can't create new trick: Incorrectly validated Difficulty field
# Description
When trying to create a new personal trick via the `/tricks/new` route, setting a difficulty results in a validation error. The message reads "Expected number, received string". As a result it is not possible to create a new personal trick at all unless no value is in the difficulty field.

I believe this issue is new since #353. So maybe @Dosbodoke could take a look.

# Expected behavior
There should only be an error it there is actually something else in the field than a number. If there is a number in the field the number should be used for the difficulty, there should be no error, and the user should be able to create the trick.

(While at it, it might be nice to only allow inputting numbers in the first place (ignoring everything else all together). But this is not necessary.)

# Screenshot

Image

### PR DESCRIPTION
**Pull request by Dosbodoke**
Fixes #362 

# How to test

Go to the new trick page and try to mess with difficulty and year fields.

DIfficulty should raise an error message if `0` or less as also if `11` or more. If the field is empty it should no error.

Year should raise an error if less than `1900` and if more than the current year (I added this validations, I don't think it makes sense to have a trick stablished at the future)

### CODE REVIEW

File: src/components/ui/customForm/TextInput.vue [hunk 1]
```diff
@@ -17,6 +17,8 @@ const props = defineProps<{
   formFieldName: string;
   placeholder?: string;
   class?: string;
+  inputMode?: string;
```
Comment (JulianDietzel) [inline src/components/ui/customForm/TextInput.vue]: What is `inputMode` used for? And is it possible to narrow the type `string` down to all the legal values (`"numeric" | "..."`)

File: src/components/ui/form/FormMessage.vue [hunk 2]
```diff
@@ -23,6 +15,6 @@ const { t } = useI18n({
     class="text-sm font-medium text-destructive"
     v-slot="{ message }"
   >
-    {{ message ? t(message) : '' }}
+    {{ message }}
```
Comment (JulianDietzel) [inline src/components/ui/form/FormMessage.vue]: This appears to not update the translation immediately when the user selects a different language. It only updates once the page is reloaded. Since it works when reloading I don't think this is a big issue. If you have an idea on how to fix this easily it would be nice to have it fixed, if this will cause you troubles or be a bit of work just leave it as is.

I had a similar issue once and solved it by using Vues `watch`-method on `i18n.locales`. Maybe this is applicable here as well: https://github.com/bastislack/highline-freestyle/blob/ac70ce038fa9bf7a70a79e4993a3be365076643c/src/routes/tricks/TrickList.vue#L76

File: src/routes/tricks/NewTrickRoute.vue [hunk 3]
```diff
@@ -28,20 +30,22 @@ const toast = useToast();
...
-    .int({ message: 'INPUT_NOT_INTEGER' })
-    .min(1, { message: 'INPUT_NUMBER_BELOW_MIN' })
-    .max(10, { message: 'INPUT_NUMBER_ABOVE_MAX' })
-    .optional(),
+  difficulty: z.union([
+    z
+      .number()
+      .int({ message: t('INPUT_NOT_INTEGER') })
+      .min(1, { message: t('INPUT_NUMBER_BELOW_MIN', { value: 1 }) })
+      .max(10, { message: t('INPUT_NUMBER_ABOVE_MAX', { value: 10 }) }),
```
Comment (JulianDietzel) [inline src/routes/tricks/NewTrickRoute.vue]: I don't think we will get there any time soon. But since this is for the user to decide I would suggest we allow values of up to 20. No need to restrict the user more than necessary.

**Review by JulianDietzel — CHANGES_REQUESTED** [review]
Thanks for the fix! It looks really good. I added some comments, the only one that I really want to see changed is the maximum difficulty the user can enter. The translation thing is such a minor issue that I don't think it needs to be fixed at this point if you don't really want to. If there is an easy quick fix though it would of course be nice

File: src/components/ui/customForm/TextInput.vue (hunk 1 above)
Comment (Dosbodoke) [reply src/components/ui/customForm/TextInput.vue]: It's for mobile keyboards, with inputMode numeric it will shown a numeric keyboard instead of the standard.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

Comment (Dosbodoke) [reply src/components/ui/customForm/TextInput.vue]: I will type it :D

File: src/components/ui/form/FormMessage.vue (hunk 2 above)
Comment (Dosbodoke) [reply src/components/ui/form/FormMessage.vue]: Yeah, the initial problem was that I couldn't pass parameters for interpolation.

Ideally, I would like the errorMessages to be imported only here and to have the following signature

`{{ message ? t(mesage, { ...messageParams }) : '' }}`

and, on the zod validation call it like `int({ message: 'INPUT_NOT_INTEGER', { value: 1 } })`

Not sure yet how I will solve this, let me take some time and iterations to figure it out.

File: src/components/ui/customForm/TextInput.vue (hunk 1 above)
Comment (JulianDietzel) [reply src/components/ui/customForm/TextInput.vue]: Thanks for the explanation, it makes sense now :+1:. Typing it sounds good to me. Looking at the docu you sent there shouldn't be too many option.

File: src/components/ui/form/FormMessage.vue (hunk 2 above)
Comment (JulianDietzel) [reply src/components/ui/form/FormMessage.vue]: I don't know if I fully understand the issue but you seem to know a lot more about vee-validate so I'll just leave it up to you how or if you want to fix it.

Do you want to iterate on it in this PR or should we merge this and you fix it in another PR when / if you find the time for it?

Comment (Dosbodoke) [reply src/components/ui/form/FormMessage.vue]: Let me try to explain better the issue...

On the error translation files, for example `error.en.json` we have defined a space for interpolation

`"INPUT_NUMBER_BELOW_MIN": "Input must be no less than {value}",`

In order to this interpolation to work correctly we need to call it with `t("INPUT_NUMBER_BELOW_MIN", { value: 1})`

Where value is the exact same keyword to interpolate.

Initially I couldn't pass it down as a prop to `ErrorMessage` so I moved the translation to the zod definition

`.min(1, { message: t('INPUT_NUMBER_BELOW_MIN', { value: 1 }) })`

So we were not passing `INPUT_NUMBER_BELOW_MIN` as the message and translating on the child component. the message was already sent in it's final state.

But then it surges the error that you pointed out, the `t()` would run only when the user trigger the form validation (on submit or edit the field), and this not include changing the language.

I just made a [commit](https://github.com/Dosbodoke/highline-freestyle/commit/39a36c6b529f9e8f859460efe4b8ff2fd000df6a) to mitigate this issue on , let me know if you think it's a good pattern. This way we are passing down the translation key `INPUT_NUMBER_BELOW_MIN` and the necessary parameters for the interpolation.

File: src/components/ui/form/FormMessage.vue [hunk 4]
```diff
@@ -1,18 +1,31 @@
...
 import messagesErrors from '@/i18n/error';
+import { i18nMerge } from '@/i18n/i18nmerge';
 
 import { useFormField } from './useFormField';
 
 const { name, formMessageId } = useFormField();
-
 const { t } = useI18n({
-  messages: messagesErrors,
+  messages: i18nMerge(messagesErrors),
```
Comment (WaldemarLehner) [inline src/components/ui/form/FormMessage.vue]: Is this intended? its been a long time since I looked at the code, but iirc this is used to merge i18n JSONs. "Merging" just 1 set should be identical to just passing it as-is

File: src/components/ui/form/FormMessage.vue [hunk 5]
```diff
@@ -1,18 +1,31 @@
...
+  values?: Record<string, string>;
+}>();
+
+// Create a computed function to translate messages
+const translateMessage = computed(() => {
+  return (message: string) => {
+    if (!message) return '';
+    return t(message, props.values || {});
+  };
+});
```
Comment (WaldemarLehner) [inline src/components/ui/form/FormMessage.vue]: Am I right to assume that the computed is needed here to "re-generate" it on language change?

File: src/components/ui/form/FormMessage.vue (hunk 2 above)
Comment (JulianDietzel) [reply src/components/ui/form/FormMessage.vue]: Thanks for the more detailed explanation. Form my understanding and talking with @WaldemarLehner  it looks good now :+1: .

We found two more things that were surprising to us, @WaldemarLehner commented on them.

File: src/components/ui/form/FormMessage.vue (hunk 4 above)
Comment (Dosbodoke) [reply src/components/ui/form/FormMessage.vue]: It's a typo, functional, but yet a typo 😬

File: src/components/ui/form/FormMessage.vue (hunk 5 above)
Comment (Dosbodoke) [reply src/components/ui/form/FormMessage.vue]: I'm more a React guy than a Vue one, really not sure how this ‘computed’ function works (I think it's like React ’useMemo’?), Claude gave me this code and I just certified it works

Comment (JulianDietzel) [reply src/components/ui/form/FormMessage.vue]: I fiddled around with it a little and I blieve Claude did a bit of an A"I" here. This does not have to be a computed function to work. The section can be simplified to:
```ts
function translateMessage (message: string): string {
  return (message) ? t(message, props.values || {}) : '';
}
```

I recognize it is getting quite nitpicky here but since this is a lot more readable, could you please swap out the section for the code I sent?

File: src/components/ui/form/FormMessage.vue (hunk 4 above)
Comment (JulianDietzel) [reply src/components/ui/form/FormMessage.vue]: Makes sense, probably a leftover from how it was before. In that case please remove the `i18nMerge` function.

**Comment by JulianDietzel** [comment]
One last thing and then I'll stop bugging you and merge this thing:

Since the difficulties can now go up to 20, the label on the field is incorrect in all languages. "1 to 10. Keep empty if unsure." should become "1 to 20. Keep empty if unsure.". The entries are the `question.difficulty` ones in the files in `/src/i18n/tricks/new/`.

Please change this. If you don't feel like it, it is totally fine, then just open a small issue for me to fix this later (so that it is not forgotten).

**Comment by Dosbodoke** [comment]
> One last thing and then I'll stop bugging you and merge this thing:
> 
> Since the difficulties can now go up to 20, the label on the field is incorrect in all languages. "1 to 10. Keep empty if unsure." should become "1 to 20. Keep empty if unsure.". The entries are the `question.difficulty` ones in the files in `/src/i18n/tricks/new/`.
> 
> Please change this. If you don't feel like it, it is totally fine, then just open a small issue for me to fix this later (so that it is not forgotten).

Don't worry bro, I really missed it. Will push a fix soon :D

**Review by JulianDietzel — APPROVED** [review]
"soon", he said, pushing in less time than it took me to eat dinner :D. Great work! Looks really good to me :+1: . At last, I will now finally merge this :)
